version: '3'
services:
  database-service:
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    image: postgres
    platform: linux/amd64
    ports:
      - 5432:5432
    restart: always
  redis-service:
    image: redis
    ports:
      - 6379:6379
  # lnd-krub:
  #   depends_on:
  #     - database-service
  #     - redis-service
  #   build: .
  #   environment:
  #     - REDIS_HOST=redis-service
  #     - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASS@database-service:5432/$POSTGRES_DB
  #   platform: linux/amd64
  #   ports:
  #     - 3000:3000
