version: '3'
services:
  bitcoin-service:
    image: polarlightning/bitcoind:24.0
    ports:
      - 18443:18443
  lightning-service:
    image: polarlightning/lnd:0.16.0-beta
    ports:
      - 10001:10001
    volumes:
      - shared-data:/lnd
  lnd-krub:
    build: .
    environment:
      - BTC_RPC_URL=bitcoin-service
      - LND_MACAROON_PATH=/alice/data/chain/bitcoin/regtest/admin.macaroon
      - LND_TLSCERT_PATH=/alice/tls.cert
    platform: linux/amd64
    ports:
      - 3000:3000
    volumes:
      - shared-data:/usr/src
  redis-service:
    image: redis
    ports:
      - 6379:6379
volumes:
  shared-data:
